name: Cypress Automation Tests

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  cypress-run:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Print Folder Structure
        run: ls -R
      
      - name: Run UI Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npx cypress run --spec "cypress/e2e/uitests/**/*.cy.js"
